spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    static-path-pattern: /res/**
  datasource:
    url: jdbc:mysql://sh-cynosdbmysql-grp-fl3phwrg.sql.tencentcdb.com:24956/bansheedata
    username: root
    password: Ma__123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jdbc:
    template:
      query-timeout: 5


schemetype:
  typeId: 1
  typeName: live
  scheme:
    schemeId: 1
    schemeName: 早餐一
    schemeDesc: 时间比较充足的情况可以选择碧海湾的水煎包

